# Basic
title: Xuanzhe Jiang
subtitle: 折腾永无止境
# welcome_message: <a href="https://github.com/onevcat/vno-jekyll" target="_blank">Download the theme</a>
description: hi，我是蒋轩哲，一枚iOS开发者，正在潜心研究软件开发技术。
creator: <a href="http://onev.cat">@onevcat</a>

# url: "http://vno.onevcat.com"

permalink: /:year/:month/:title/

# Format
highlighter: plain
markdown: kramdown
kramdown:
  input: GFM
  extensions:
    - autolink
    - footnotes
    - smart
  use_coderay: true
  syntax_highlighter: rouge
  coderay:
    coderay_line_numbers:  nil

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: slate

# The blog button should not be removed.
blog_button:
    title: 博客
    description: 博客

# Navigation buttons in the front page.
# nav:
    # - {title: Projects, description: My Projects, url: 'http://project.onevcat.com'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    # disqus: vno-jekyll
    # duoshuo: 
    
# Social
social:
    weibo: 蒋哥传媒JGCM
    github: XuanzheJiang
    stackoverflow: http://stackoverflow.com/users/6058532/jgcm
    douban: jgcm
    twitter: 蒋轩哲
    mail: jgcm@live.cn

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
